import React, { useEffect, useState } from "react";
import axios from "axios";
import "./HotelAmendment.css";

function HotelAmendment() {
  const [amendments, setAmendments] = useState([]);
  const [filters, setFilters] = useState({
    key: "",
    value: "",
    fromDate: "",
    toDate: ""
  });

  const fetchAmendments = async () => {
    try {
      const res = await axios.get("/api/hotel-amendments", {
        params: filters
      });
      setAmendments(res.data);
    } catch (err) {
      console.error("Error loading data:", err);
    }
  };

  useEffect(() => {
    fetchAmendments();
  }, []);

  const handleSearch = () => {
    fetchAmendments();
  };

  const resetSearch = () => {
    setFilters({ key: "", value: "", fromDate: "", toDate: "" });
    fetchAmendments();
  };

  return (
    <div className="hotel-amendment-container">
      <h2>Hotel Amendments List</h2>

      <div className="filters">
        <select
          value={filters.key}
          onChange={(e) => setFilters({ ...filters, key: e.target.value })}
        >
          <option value="">Select key</option>
          <option value="bookingRefNo">Booking Ref No.</option>
          <option value="hotelName">Hotel Name</option>
          <option value="travellerName">Traveller Name</option>
        </select>
        <input
          type="text"
          placeholder="Value"
          value={filters.value}
          onChange={(e) => setFilters({ ...filters, value: e.target.value })}
        />
        <input
          type="date"
          value={filters.fromDate}
          onChange={(e) => setFilters({ ...filters, fromDate: e.target.value })}
        />
        <input
          type="date"
          value={filters.toDate}
          onChange={(e) => setFilters({ ...filters, toDate: e.target.value })}
        />
        <button onClick={handleSearch}>Search</button>
        <button onClick={resetSearch}>Reset</button>
      </div>

      <table className="amendment-table">
        <thead>
          <tr>
            <th>Ref No.</th>
            <th>Amendment ID</th>
            <th>Type</th>
            <th>Status</th>
            <th>Hotel</th>
            <th>Customer</th>
            <th>Source</th>
            <th>Traveller</th>
            <th>Checkin</th>
            <th>Checkout</th>
            <th>City</th>
            <th>Country</th>
            <th>Booking Status</th>
            <th>Admin Remark</th>
            <th>Generated By</th>
            <th>AMD Staff</th>
            <th>Created</th>
            <th>Summary</th>
          </tr>
        </thead>
        <tbody>
          {amendments.length > 0 ? (
            amendments.map((item) => (
              <tr key={item._id}>
                <td>{item.bookingRefNo}</td>
                <td>{item.amendmentId}</td>
                <td>{item.amendmentType}</td>
                <td>{item.amendmentStatus}</td>
                <td>{item.hotelName}</td>
                <td>{item.companyName}</td>
                <td>{item.bookingSource}</td>
                <td>{item.travellerName}</td>
                <td>{item.checkinDate?.slice(0, 10)}</td>
                <td>{item.checkoutDate?.slice(0, 10)}</td>
                <td>{item.city}</td>
                <td>{item.country}</td>
                <td>{item.bookingStatus}</td>
                <td>{item.adminRemark}</td>
                <td>{item.generatedBy}</td>
                <td>{item.amdStaff}</td>
                <td>{new Date(item.createdAt).toLocaleDateString()}</td>
                <td>{item.summary}</td>
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan="18">No Amendments Found</td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

export default HotelAmendment;
