// // import React, { useEffect, useState } from "react";
// // import axios from "axios";
// // import "./HotelAmendment.css";

// // function HotelAmendment() {
// //   const [amendments, setAmendments] = useState([]);
// //   const [filters, setFilters] = useState({
// //     key: "",
// //     value: "",
// //     fromDate: "",
// //     toDate: ""
// //   });

// //   const fetchAmendments = async () => {
// //     try {
// //       const res = await axios.get("/api/hotel-amendments", {
// //         params: filters
// //       });
// //       setAmendments(res.data);
// //     } catch (err) {
// //       console.error("Error loading data:", err);
// //     }
// //   };

// //   useEffect(() => {
// //     fetchAmendments();
// //   }, []);

// //   const handleSearch = () => {
// //     fetchAmendments();
// //   };

// //   const resetSearch = () => {
// //     setFilters({ key: "", value: "", fromDate: "", toDate: "" });
// //     fetchAmendments();
// //   };

// //   return (
// //     <div className="hotel-amendment-container">
// //       <h2>Hotel Amendments List</h2>

// //       <div className="filters">
// //         <select
// //           value={filters.key}
// //           onChange={(e) => setFilters({ ...filters, key: e.target.value })}
// //         >
// //           <option value="">Select key</option>
// //           <option value="bookingRefNo">Booking Ref No.</option>
// //           <option value="hotelName">Hotel Name</option>
// //           <option value="travellerName">Traveller Name</option>
// //         </select>
// //         <input
// //           type="text"
// //           placeholder="Value"
// //           value={filters.value}
// //           onChange={(e) => setFilters({ ...filters, value: e.target.value })}
// //         />
// //         <input
// //           type="date"
// //           value={filters.fromDate}
// //           onChange={(e) => setFilters({ ...filters, fromDate: e.target.value })}
// //         />
// //         <input
// //           type="date"
// //           value={filters.toDate}
// //           onChange={(e) => setFilters({ ...filters, toDate: e.target.value })}
// //         />
// //         <button onClick={handleSearch}>Search</button>
// //         <button onClick={resetSearch}>Reset</button>
// //       </div>

// //       <table className="amendment-table">
// //         <thead>
// //           <tr>
// //             <th>Ref No.</th>
// //             <th>Amendment ID</th>
// //             <th>Type</th>
// //             <th>Status</th>
// //             <th>Hotel</th>
// //             <th>Customer</th>
// //             <th>Source</th>
// //             <th>Traveller</th>
// //             <th>Checkin</th>
// //             <th>Checkout</th>
// //             <th>City</th>
// //             <th>Country</th>
// //             <th>Booking Status</th>
// //             <th>Admin Remark</th>
// //             <th>Generated By</th>
// //             <th>AMD Staff</th>
// //             <th>Created</th>
// //             <th>Summary</th>
// //           </tr>
// //         </thead>
// //         <tbody>
// //           {amendments.length > 0 ? (
// //             amendments.map((item) => (
// //               <tr key={item._id}>
// //                 <td>{item.bookingRefNo}</td>
// //                 <td>{item.amendmentId}</td>
// //                 <td>{item.amendmentType}</td>
// //                 <td>{item.amendmentStatus}</td>
// //                 <td>{item.hotelName}</td>
// //                 <td>{item.companyName}</td>
// //                 <td>{item.bookingSource}</td>
// //                 <td>{item.travellerName}</td>
// //                 <td>{item.checkinDate?.slice(0, 10)}</td>
// //                 <td>{item.checkoutDate?.slice(0, 10)}</td>
// //                 <td>{item.city}</td>
// //                 <td>{item.country}</td>
// //                 <td>{item.bookingStatus}</td>
// //                 <td>{item.adminRemark}</td>
// //                 <td>{item.generatedBy}</td>
// //                 <td>{item.amdStaff}</td>
// //                 <td>{new Date(item.createdAt).toLocaleDateString()}</td>
// //                 <td>{item.summary}</td>
// //               </tr>
// //             ))
// //           ) : (
// //             <tr>
// //               <td colSpan="18">No Amendments Found</td>
// //             </tr>
// //           )}
// //         </tbody>
// //       </table>
// //     </div>
// //   );
// // }

// // export default HotelAmendment;
// import React, { useEffect, useState } from "react";
// import axios from "axios";
// import "./HotelAmendment.css";

// function HotelAmendment() {
//   const [amendments, setAmendments] = useState([]);
//   const [editId, setEditId] = useState(null);

//   const [filters, setFilters] = useState({
//     key: "",
//     value: "",
//     fromDate: "",
//     toDate: "",
//   });

//   const [form, setForm] = useState({
//     bookingRefNo: "",
//     amendmentId: "",
//     amendmentType: "",
//     amendmentStatus: "",
//     hotelName: "",
//     companyName: "",
//     bookingSource: "",
//     travellerName: "",
//     checkinDate: "",
//     checkoutDate: "",
//     city: "",
//     country: "",
//     bookingStatus: "",
//     adminRemark: "",
//     generatedBy: "",
//     amdStaff: "",
//     summary: "",
//   });

//   // Fetch Amendments
//   const fetchAmendments = async () => {
//     try {
//       const res = await axios.get("/api/hotel-amendments", {
//         params: filters,
//       });
//       setAmendments(res.data);
//     } catch (err) {
//       console.error("Error loading data:", err);
//     }
//   };

//   useEffect(() => {
//     fetchAmendments();
//   }, []);

//   // Add / Update
//   const handleSubmit = async (e) => {
//     e.preventDefault();

//     if (editId) {
//       await axios.put(`/api/hotel-amendments/${editId}`, form);
//     } else {
//       await axios.post("/api/hotel-amendments", form);
//     }

//     setEditId(null);
//     resetForm();
//     fetchAmendments();
//   };

//   const resetForm = () => {
//     setForm({
//       bookingRefNo: "",
//       amendmentId: "",
//       amendmentType: "",
//       amendmentStatus: "",
//       hotelName: "",
//       companyName: "",
//       bookingSource: "",
//       travellerName: "",
//       checkinDate: "",
//       checkoutDate: "",
//       city: "",
//       country: "",
//       bookingStatus: "",
//       adminRemark: "",
//       generatedBy: "",
//       amdStaff: "",
//       summary: "",
//     });
//   };

//   const handleEdit = (item) => {
//     setEditId(item._id);
//     setForm(item);
//   };

//   const handleDelete = async (id) => {
//     await axios.delete(`/api/hotel-amendments/${id}`);
//     fetchAmendments();
//   };

//   const handleSearch = () => fetchAmendments();

//   const resetSearch = () => {
//     setFilters({ key: "", value: "", fromDate: "", toDate: "" });
//     fetchAmendments();
//   };

//   return (
//     <div className="hotel-amendment-container">
//       <h2>Hotel Amendments List</h2>

//       {/* FILTERS */}
//       <div className="filters">
//         <select
//           value={filters.key}
//           onChange={(e) => setFilters({ ...filters, key: e.target.value })}
//         >
//           <option value="">Select key</option>
//           <option value="bookingRefNo">Booking Ref No.</option>
//           <option value="hotelName">Hotel Name</option>
//           <option value="travellerName">Traveller Name</option>
//         </select>

//         <input
//           type="text"
//           placeholder="Value"
//           value={filters.value}
//           onChange={(e) => setFilters({ ...filters, value: e.target.value })}
//         />

//         <input
//           type="date"
//           value={filters.fromDate}
//           onChange={(e) => setFilters({ ...filters, fromDate: e.target.value })}
//         />

//         <input
//           type="date"
//           value={filters.toDate}
//           onChange={(e) => setFilters({ ...filters, toDate: e.target.value })}
//         />

//         <button onClick={handleSearch}>Search</button>
//         <button onClick={resetSearch}>Reset</button>
//       </div>

//       {/* ADD + EDIT FORM */}
//       <form className="amendment-form" onSubmit={handleSubmit}>
//         {Object.keys(form).map((field) => (
//           <input
//             key={field}
//             type={field.toLowerCase().includes("date") ? "date" : "text"}
//             placeholder={field}
//             value={
//               field.includes("Date")
//                 ? form[field]?.slice(0, 10)
//                 : form[field]
//             }
//             onChange={(e) => setForm({ ...form, [field]: e.target.value })}
//           />
//         ))}
//         <button type="submit">{editId ? "Update" : "Add Amendment"}</button>
//       </form>

//       {/* TABLE */}
//       <table className="amendment-table">
//         <thead>
//           <tr>
//             <th>Ref No.</th>
//             <th>Amend ID</th>
//             <th>Type</th>
//             <th>Status</th>
//             <th>Hotel</th>
//             <th>Customer</th>
//             <th>Source</th>
//             <th>Traveller</th>
//             <th>Check-in</th>
//             <th>Checkout</th>
//             <th>City</th>
//             <th>Country</th>
//             <th>Book Status</th>
//             <th>Admin Remark</th>
//             <th>Generated By</th>
//             <th>AMD Staff</th>
//             <th>Created</th>
//             <th>Summary</th>
//             <th>Action</th>
//           </tr>
//         </thead>

//         <tbody>
//           {amendments.length > 0 ? (
//             amendments.map((item) => (
//               <tr key={item._id}>
//                 <td>{item.bookingRefNo}</td>
//                 <td>{item.amendmentId}</td>
//                 <td>{item.amendmentType}</td>
//                 <td>{item.amendmentStatus}</td>
//                 <td>{item.hotelName}</td>
//                 <td>{item.companyName}</td>
//                 <td>{item.bookingSource}</td>
//                 <td>{item.travellerName}</td>
//                 <td>{item.checkinDate?.slice(0, 10)}</td>
//                 <td>{item.checkoutDate?.slice(0, 10)}</td>
//                 <td>{item.city}</td>
//                 <td>{item.country}</td>
//                 <td>{item.bookingStatus}</td>
//                 <td>{item.adminRemark}</td>
//                 <td>{item.generatedBy}</td>
//                 <td>{item.amdStaff}</td>
//                 <td>{new Date(item.createdAt).toLocaleDateString()}</td>
//                 <td>{item.summary}</td>

//                 <td>
//                   <button onClick={() => handleEdit(item)}>✏️</button>
//                   <button onClick={() => handleDelete(item._id)}>🗑️</button>
//                 </td>
//               </tr>
//             ))
//           ) : (
//             <tr>
//               <td colSpan="19">No Amendments Found</td>
//             </tr>
//           )}
//         </tbody>
//       </table>
//     </div>
//   );
// }

// export default HotelAmendment;
import React, { useEffect, useState } from "react";
import axios from "axios";
import "./HotelAmendment.css";

function HotelAmendment() {
  const [amendments, setAmendments] = useState([]);
  const [editId, setEditId] = useState(null);

  const [filters, setFilters] = useState({
    key: "",
    value: "",
    fromDate: "",
    toDate: "",
  });

  const [form, setForm] = useState({
    bookingRefNo: "",
    amendmentId: "",
    amendmentType: "",
    amendmentStatus: "",
    hotelName: "",
    companyName: "",
    bookingSource: "",
    travellerName: "",
    checkinDate: "",
    checkoutDate: "",
    city: "",
    country: "",
    bookingStatus: "",
    adminRemark: "",
    generatedBy: "",
    amdStaff: "",
    summary: "",
  });

  // Fetch all amendments
  const fetchAmendments = async () => {
    try {
      const res = await axios.get("/api/hotel-amendments", {
        params: filters,
      });
      setAmendments(res.data);
    } catch (err) {
      console.error("Error loading data:", err);
    }
  };

  useEffect(() => {
    fetchAmendments();
  }, []);

  // Add or Update
  const handleSubmit = async (e) => {
    e.preventDefault();

    if (editId) {
      await axios.put(`/api/hotel-amendments/${editId}`, form);
    } else {
      await axios.post("/api/hotel-amendments", form);
    }

    setEditId(null);
    resetForm();
    fetchAmendments();
  };

  const resetForm = () => {
    setForm({
      bookingRefNo: "",
      amendmentId: "",
      amendmentType: "",
      amendmentStatus: "",
      hotelName: "",
      companyName: "",
      bookingSource: "",
      travellerName: "",
      checkinDate: "",
      checkoutDate: "",
      city: "",
      country: "",
      bookingStatus: "",
      adminRemark: "",
      generatedBy: "",
      amdStaff: "",
      summary: "",
    });
  };

  const handleEdit = (item) => {
    setEditId(item._id);
    setForm({
      ...item,
      checkinDate: item.checkinDate?.slice(0, 10) || "",
      checkoutDate: item.checkoutDate?.slice(0, 10) || "",
    });
  };

  const handleDelete = async (id) => {
    await axios.delete(`/api/hotel-amendments/${id}`);
    fetchAmendments();
  };

  const handleSearch = () => fetchAmendments();

  const resetSearch = () => {
    setFilters({ key: "", value: "", fromDate: "", toDate: "" });
    fetchAmendments();
  };

  return (
    <div className="hotel-amendment-container">
      <h2>Hotel Amendments List</h2>

      {/* FILTER SECTION */}
      <div className="filters">
        <select
          value={filters.key}
          onChange={(e) => setFilters({ ...filters, key: e.target.value })}
        >
          <option value="">Select key</option>
          <option value="bookingRefNo">Booking Ref No</option>
          <option value="hotelName">Hotel Name</option>
          <option value="travellerName">Traveller Name</option>
        </select>

        <input
          type="text"
          placeholder="Search value"
          value={filters.value}
          onChange={(e) => setFilters({ ...filters, value: e.target.value })}
        />

        <input
          type="date"
          value={filters.fromDate}
          onChange={(e) => setFilters({ ...filters, fromDate: e.target.value })}
        />

        <input
          type="date"
          value={filters.toDate}
          onChange={(e) => setFilters({ ...filters, toDate: e.target.value })}
        />

        <button onClick={handleSearch}>Search</button>
        <button onClick={resetSearch}>Reset</button>
      </div>

      {/* ADD / EDIT FORM */}
      <form className="amendment-form" onSubmit={handleSubmit}>
        {Object.keys(form).map((field) => (
          <input
            key={field}
            type={
              field === "checkinDate" || field === "checkoutDate"
                ? "date"
                : "text"
            }
            placeholder={field}
            value={form[field]}
            onChange={(e) => setForm({ ...form, [field]: e.target.value })}
          />
        ))}
        <button type="submit">{editId ? "Update" : "Add Amendment"}</button>
      </form>

      {/* TABLE */}
      <table className="amendment-table">
        <thead>
          <tr>
            <th>Ref No</th>
            <th>Amend ID</th>
            <th>Type</th>
            <th>Status</th>
            <th>Hotel</th>
            <th>Customer</th>
            <th>Source</th>
            <th>Traveller</th>
            <th>Check-in</th>
            <th>Checkout</th>
            <th>City</th>
            <th>Country</th>
            <th>Book Status</th>
            <th>Admin Remark</th>
            <th>Generated By</th>
            <th>AMD Staff</th>
            <th>Created</th>
            <th>Summary</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          {amendments.length > 0 ? (
            amendments.map((item) => (
              <tr key={item._id}>
                <td data-label="Ref No">{item.bookingRefNo}</td>
                <td data-label="Amend ID">{item.amendmentId}</td>
                <td data-label="Type">{item.amendmentType}</td>
                <td data-label="Status">{item.amendmentStatus}</td>
                <td data-label="Hotel">{item.hotelName}</td>
                <td data-label="Customer">{item.companyName}</td>
                <td data-label="Source">{item.bookingSource}</td>
                <td data-label="Traveller">{item.travellerName}</td>
                <td data-label="Check-in">
                  {item.checkinDate?.slice(0, 10)}
                </td>
                <td data-label="Checkout">
                  {item.checkoutDate?.slice(0, 10)}
                </td>
                <td data-label="City">{item.city}</td>
                <td data-label="Country">{item.country}</td>
                <td data-label="Book Status">{item.bookingStatus}</td>
                <td data-label="Admin Remark">{item.adminRemark}</td>
                <td data-label="Generated By">{item.generatedBy}</td>
                <td data-label="AMD Staff">{item.amdStaff}</td>
                <td data-label="Created">
                  {new Date(item.createdAt).toLocaleDateString()}
                </td>
                <td data-label="Summary">{item.summary}</td>

                <td data-label="Action">
                  <button onClick={() => handleEdit(item)}>✏️</button>
                  <button onClick={() => handleDelete(item._id)}>🗑️</button>
                </td>
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan="19">No Amendments Found</td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

export default HotelAmendment;
